/* eslint-disable @next/next/no-img-element */
import styles from '../../styles/Slug.module.css'
import { GraphQLClient, gql } from 'graphql-request';

import Navbar from '../../components/Navbar';
import Footer from '../../components/Footer';
import Head from 'next/head';

const graphcms = new GraphQLClient(
  "https://api-sa-east-1.hygraph.com/v2/cl5irmblc0xmy01uj4674cuk2/master"
);

const QUERY = gql`
  query Post($slug: String!){
    post(where: {slug: $slug}) {
      id,
      title,
      slug,
      datePublished,
      author {
        id,
        name,
        avatar {
          url
        }
      }
      content {
        html
      }
      coverPhoto {
        id,
        url
      }
    }
  }
`;

const SLUGLIST = gql`
  {
    posts {
      slug
    }
  }
`;

export async function getStaticPaths() {
  const { posts } = await graphcms.request(SLUGLIST);
  return {
    paths: posts.map((post) => ({ params: { slug: post.slug } })),
    fallback: false,
  };
}

export async function getStaticProps({ params }) {
  const slug = params.slug;
  const data = await graphcms.request(QUERY, { slug });
  const post = data.post;
  return{
    props: {
      post,
    },
    revalidate: 30,
  };
}

export default function BlogPost({post}) {
  return (
    <div>
      <Head>
        <title>Coffee and Code</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/logo-head.png" />
      </Head>
      <Navbar />
        <main className={styles.blog}>
          <img src={post.coverPhoto.url} className={styles.cover} alt={post.title}/>
          <div className={styles.title}>
            <div className={styles.authdetails}>
              <img src={post.author.avatar.url} alt="" />
              <div className={styles.authtext}>
                <h6>Por {post.author.name}</h6>
                <h6 className={styles.date}>{post.datePublished}</h6>
              </div>
            </div>
          </div>
          <h2>{post.title}</h2>
          <div 
            className={styles.content}
            dangerouslySetInnerHTML={{ __html: post.content.html }}>
          </div>
        </main>
      <Footer />
    </div>
  )
}